steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        touch .env
        echo "SECRET_KEY=$_SECRET_KEY" > .env
        echo "API_KEY=$_API_KEY" > .env
        gcloud app deploy
timeout: '1600s'