steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "API_KEY=$$_API_KEY" > .env
        gcloud config set app/cloud_build_timeout 1600
        gcloud app deploy
timeout: '1600s'